# Execution environment
exe_env=remote
headless=true
incognito=true

# Base URL
url=https://tutorialsninja.com/demo/

# Selenium Grid
grid_url=http://localhost:4444/wd/hub

# Login user (default)
username=Tomas Shelby
email=piwene6598@badfist.com
password=Qaz@123
