# Execution environment: local or remote
exe_env=local

# These are used ONLY when exe_env=local
headless=false
incognito=true

# Application URL
url=https://tutorialsninja.com/demo/

# Selenium Grid URL (used when exe_env=remote)
grid_url=http://localhost:4444/wd/hub

# Test data
username=Tomas Shelby
email=piwene6598@badfist.com
password=Qaz@123
searchProduct=HP Laptop

expected.day=18
expected.month=January
expected.year=2026
expected.date=2026-01-18
